server:
  port: 8080

spring:
  datasource:
    url: jdbc:mysql://192.168.1.5:3306/security?serverTimezone=Asia/Shanghai
    driver-class-name:  com.mysql.cj.jdbc.Driver
    username: root
    password: Aa123456

  jpa:
    database: mysql
    show-sql: true
    hibernate:
      ddl-auto: update

  redis:
    host: localhost
    port: 6379
    password:
    database: 0           #Redis默认情况下有16个分片，这里配置具体使用的分片，默认是0
    timeout: 5000         #连接超时时间(ms)

jwt:
  #签名
  signingKey: fucker
  #过期时间（单位：秒）
  expiration: 600
